name: llama_grammar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - openpyxl
  - matplotlib
  - scikit-learn
  - seaborn
  - shap
  - gensim
  - umap-learn
  - hdbscan
  - sentence-transformers
  - transformers
  - pip
  - pip:
      - llama-cpp-python
      - trl
      - tqdm
      - fuzzywuzzy
      - python-docx
      - fastapi
      - uvicorn
      - chromadb
      - huggingface_hub
      - torch
      
